#!/bin/bash

export PROJECT_NAME="GIT-HOOK"

ISSUE_ID_SEQ=1

get_branch_name(){
    printf $PROJECT_NAME"-%05d" $ISSUE_ID_SEQ
    sed -i "s/^ISSUE_ID_SEQ\=.*/ISSUE_ID_SEQ=$((ISSUE_ID_SEQ + 1))/" utils
}

create_branch() {
    echo `git checkout -b $(get_branch_name)'-'${1}`
}